CREATE DATABASE auth;
CREATE DATABASE courses;
CREATE DATABASE "order";
CREATE DATABASE payment;

CREATE USER auth WITH PASSWORD 'auth';
CREATE USER courses WITH PASSWORD 'courses';
CREATE USER "order" WITH PASSWORD 'order';
CREATE USER payment WITH PASSWORD 'payment';

GRANT ALL PRIVILEGES ON DATABASE auth TO auth;
GRANT ALL PRIVILEGES ON DATABASE courses TO courses;
GRANT ALL PRIVILEGES ON DATABASE "order" TO "order";
GRANT ALL PRIVILEGES ON DATABASE payment TO payment;
